name: "Build Armbian"
on:
  workflow_dispatch:
jobs:
  build-armbian:
    runs-on: ubuntu-latest
    steps:
      - uses: vamrs-feng/build@main
        with:
          armbian_release:   "jammy"                        # userspace
          armbian_target:    "build"                        # build=image, kernel=kernel
          armbian_board:     "rock-5b"                   # build target
          armbian_kernel_branch:  "legacy"
          armbian_ui:         "gnome"
          armbian_compress:   "xz"


